---
title: "Start template, master file"
author: "Laure Cougnaud, Kirsten Van Hoorde, OpenAnalytics"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  bookdown::html_document2:
    css: css/custom.css
    toc: true
    toc_depth: 4
    number_sections: true
    toc_float:
      collapsed: true
---


<!---
Copy this template in your working directory (where you want to run the report).
You can make use of the function getPathStartTemplate(). 

This template can be used as a starting document for any new dataset
-->

```{r copyStartTemplate, echo = FALSE, eval = FALSE}

	# copy start template to working directory
	library(exampleRTemplatePackage)
	file.copy(from = getPathStartTemplate(), to = "./")

```

```{r runDocument, echo = FALSE, eval = FALSE}

	## This chunk contains code to render the document.

	rm(list = ls())
	detach('package:exampleRTemplatePackage', unload = TRUE);library(exampleReportingPackage)
	system.time(rmarkdown::render("startTemplate.Rmd"))
	
```

```{r inputOutputPath, echo = FALSE}

	# output path (can differs than working directory)
	outputPath <- file.path(getwd(), "output/")
	
	if (!file.exists(outputPath)) dir.create(outputPath, recursive = TRUE)
	
	# When working on a windows computer it should be "/Users/..." instead of "C:/Users/..."
	if(.Platform$OS.type == "windows") outputPath <- paste0("/", paste(unlist(strsplit(outputPath, split = "/"))[-1], collapse = "/"),"/")
	
```

```{r optionsChunk, echo = FALSE, message = FALSE, warning=FALSE}

	## Chunk with options for knitr. This chunk should not be modified.

	knitr::opts_chunk$set(
		eval = TRUE,
		echo = FALSE, 
		message = FALSE,
		cache = FALSE,
		warning = FALSE,
		error = FALSE,
		comment = "#",
	  	tidy = FALSE,
		collapse = TRUE,
		results = "asis",
		root.dir = outputPath)
	knitr::opts_knit$set(
		root.dir = getwd())
	
	options(warn = 1, width = 200)
	
```

```{r requiredLibraries}

	library(bookdown)

```

<!-- Loading the package with the child templates and functions for the creation of this report. -->

```{r libraries}

	library(knitr)
	
	# load R template package
	library(exampleRTemplatePackage)

```

```{r inputParameters-data}

	# load dataset
	data(iris)
	
	## input parameters - data
	
	# 'dataset': data.frame/matrix with variables
	dataset <- iris
	# 'variables': column names of 'dataset' with numeric variables 
	variables <- grep("Species", colnames(iris), 
		invert = TRUE, value = TRUE) 
	# 'covariate': factor variable with subset of data
	covariate <- "Species"
	
```

```{r inputParameters-analysis}

	## input parameters for boxplot
	
	# 'boxplot': boolean, should the 'variables' be represented with a boxplot versus the 'covariate'?
    boxPlot <- TRUE
	# 'boxplotColorVariables': vector with color for each boxplot
	# with names corresponding to the names of the 'variables' 
	# (for color specific of each variable)
    boxPlotColorVariables <- c("red", "magenta", "blue", "cyan")
    names(boxPlotColorVariables) <- c("Sepal.Length", "Sepal.Width", 
		"Petal.Length", "Petal.Width")
    
	## input parameter for pairwise comparison plot of each pair of variables

	# 'pairwiseComparison': boolean, should each pair of 'variables'
	# be represented in paired scatterplot 
	# (with the function 'pairwiseComparison' of the package)
	pairwiseComparison <- TRUE
	# 'pairwiseComparisonPlotColorVariable': column name of the dataset used to
	# color the points in the scatterplot
    pairwiseComparisonPlotColorVariable <- "Species" 
	# 'typePlot': type of the plot, either 'baseR', 'ggplot2', 'rbokeh', or 'plotly'
	typePlot <- "plotly"
	
	## input parameters for a linear discriminant analysis of the data
	
	# 'includeLda': boolean, should a linear discriminant analysis be executed on the data?
	includeLda <- TRUE
	# 'covariateLda': column name of 'dataset' with groups for the discriminant analysis
	covariateLda <- covariate
	# 'dimensionsLda': numeric, number of linear discriminants to be usred for the plot
	dimensionsLda <- 4

```

<!-- call/run child template with the analysis, contained in the `exampleReportingPackage` package-->
```{r runAnalysis, child = getPathTemplate("exampleTemplate_child.Rmd")}

```
